version: '3'

services:
  web:
    build:
      context: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - quiz-network
    environment:
      FLASK_ENV: development

  test:
    build: ./app
    command: python -m unittest discover -s app -p 'test_app.py'
    volumes:
      - ./app:/app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge