version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development

  test:
    build: ./app
    command: python -m unittest discover -s app -p 'test_app.py'
    volumes:
      - ./app:/app